# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(372, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.NameBracket = QtWidgets.QLineEdit(self.centralwidget)
        self.NameBracket.setAlignment(QtCore.Qt.AlignCenter)
        self.NameBracket.setObjectName("NameBracket")
        self.verticalLayout_3.addWidget(self.NameBracket)
        self.PasswordBracket = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordBracket.setAlignment(QtCore.Qt.AlignCenter)
        self.PasswordBracket.setObjectName("PasswordBracket")
        self.verticalLayout_3.addWidget(self.PasswordBracket)
        self.LogInButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogInButton.setFlat(False)
        self.LogInButton.setObjectName("LogInButton")
        self.verticalLayout_3.addWidget(self.LogInButton)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RememberMeBox = QtWidgets.QCheckBox(self.centralwidget)
        self.RememberMeBox.setObjectName("RememberMeBox")
        self.horizontalLayout.addWidget(self.RememberMeBox)
        self.ShowPasswordBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ShowPasswordBox.setObjectName("ShowPasswordBox")
        self.horizontalLayout.addWidget(self.ShowPasswordBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ForgotPasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.ForgotPasswordButton.setObjectName("ForgotPasswordButton")
        self.verticalLayout_2.addWidget(self.ForgotPasswordButton)
        self.RegistrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegistrationButton.setObjectName("RegistrationButton")
        self.verticalLayout_2.addWidget(self.RegistrationButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NameBracket.setText(_translate("MainWindow", "Name"))
        self.PasswordBracket.setText(_translate("MainWindow", "Password"))
        self.LogInButton.setText(_translate("MainWindow", "LogIn"))
        self.RememberMeBox.setText(_translate("MainWindow", "RememberMe"))
        self.ShowPasswordBox.setText(_translate("MainWindow", "ShowPassword"))
        self.ForgotPasswordButton.setText(_translate("MainWindow", "ForgotPassword"))
        self.RegistrationButton.setText(_translate("MainWindow", "Registration"))
